### ISSUE TITLE
Not working on Java Android Studio

### ISSUE THREAD

**Issue by mrazaimtiaz** [jnasmartcardio/jnasmartcardio#39]
when I try to connect this with the android app built in android studio, I can not import TerminalFactory, whereas Smartcardio() class is working but without terminalFactory things are not working.

<img width="679" alt="Screen Shot 2022-07-18 at 9 40 32 AM" src="https://user-images.githubusercontent.com/46282781/179456970-d5935fa2-d158-4c01-865e-3a1b2563e9bf.png">

ThankYou

**Comment by yonran** [comment]
`javax.smartcardio` is part of Oracle JRE, but it is not included in the [Android API packages](https://developer.android.com/reference/packages). So the [Smartcardio](https://github.com/jnasmartcardio/jnasmartcardio/blob/master/src/main/java/jnasmartcardio/Smartcardio.java) class will not load if the javax.smartcardio interfaces can’t be found.

Furthermore, this java library jnasmartcardio depends on the C shared library [libpcsclite.so.1](https://pcsclite.apdu.fr/) on Linux to talk to the pcscd daemon, which typically communicates to a smart card reader connected on USB. I don’t think pcscd and libpcsclite.so.1 are installed on most Android devices unless you’ve rooted it and installed custom software. So even if you tried to use the [Winscard](https://github.com/jnasmartcardio/jnasmartcardio/blob/master/src/main/java/jnasmartcardio/Winscard.java) class directly (which does not rely on javax.smartcardio), the call to `com.sun.jna.Native.loadLibrary("libpcsclite.so.1", jnasmartcardio.Winscard.WinscardLibrary.class)` will probably fail because the shared library libpcsclite.so.1 does not exist in /vendor/lib or /system/lib.

If you are using an NFC card and device, android has their own packages under `android.nfc` e.g. [IsoDep](https://developer.android.com/reference/android/nfc/tech/IsoDep) to communicate with a card that speaks ISO 14443-4 over NFC. Please try that instead.

If you do have a pcsc-compatible smart card reader, please describe your setup more fully.

**Comment by mrazaimtiaz** [comment]
Thanks for the detailed reply, since this library is not supported in android I am closing the issue.

**Comment by yonran** [comment]
Good luck!
